# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        flake8 . --count --show-source --statistics

    - name: Check Python DocStrings
      run: |
        pydocstyle

    - name: Python code pytest & coverage report
      run: |
        coverage run -m pytest
        coverage report --include=./* -m

    - name: Build JSDoc
      uses: andstor/jsdoc-action@v1
      with:
        source_dir: src
        recurse: true
        output_dir: docs/build

    - name: Build pdf docs
      uses: ammaraskar/sphinx-action@master
      with:
        pre-build-command: "apt-get update -y && apt-get install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended"
        build-command: "make latexpdf"

    - name: upload pdf artifact
      uses: actions/upload-artifact@v2
      with:
        name: pdf-docs-artifact
        path: docs/build/latex/210habittracker.pdf

    - name: upload jsdocs
      uses: actions/upload-artifact@v2
      with:
        name: js-documentation
        path: docs/build/

    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm install jest --global
    - run: npm run test
